name: keras-yolo3
channels:
- defaults
dependencies:
- cython
- matplotlib
- numpy
- keras
- tensorflow-gpu
- nb_conda
- pandas
- python=3.6
- ipywidgets
- pip:
  - Pillow
  - tqdm
  - opencv-python
  - opencv-contrib-python
